//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deveel {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deveel.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid rounding mode 的本地化字符串。
        /// </summary>
        internal static string math00 {
            get {
                return ResourceManager.GetString("math00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 power of ten too big 的本地化字符串。
        /// </summary>
        internal static string math01 {
            get {
                return ResourceManager.GetString("math01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale out of range. 的本地化字符串。
        /// </summary>
        internal static string math02 {
            get {
                return ResourceManager.GetString("math02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infinite or NaN 的本地化字符串。
        /// </summary>
        internal static string math03 {
            get {
                return ResourceManager.GetString("math03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Division by zero 的本地化字符串。
        /// </summary>
        internal static string math04 {
            get {
                return ResourceManager.GetString("math04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Non-terminating decimal expansion; no exact representable decimal result. 的本地化字符串。
        /// </summary>
        internal static string math05 {
            get {
                return ResourceManager.GetString("math05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Division impossible 的本地化字符串。
        /// </summary>
        internal static string math06 {
            get {
                return ResourceManager.GetString("math06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Operation 的本地化字符串。
        /// </summary>
        internal static string math07 {
            get {
                return ResourceManager.GetString("math07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rounding necessary 的本地化字符串。
        /// </summary>
        internal static string math08 {
            get {
                return ResourceManager.GetString("math08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overflow 的本地化字符串。
        /// </summary>
        internal static string math09 {
            get {
                return ResourceManager.GetString("math09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underflow 的本地化字符串。
        /// </summary>
        internal static string math0A {
            get {
                return ResourceManager.GetString("math0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null unscaled value 的本地化字符串。
        /// </summary>
        internal static string math0B {
            get {
                return ResourceManager.GetString("math0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Digits &lt; 0 的本地化字符串。
        /// </summary>
        internal static string math0C {
            get {
                return ResourceManager.GetString("math0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null RoundingMode 的本地化字符串。
        /// </summary>
        internal static string math0D {
            get {
                return ResourceManager.GetString("math0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bad string format 的本地化字符串。
        /// </summary>
        internal static string math0E {
            get {
                return ResourceManager.GetString("math0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bad precision value 的本地化字符串。
        /// </summary>
        internal static string math0F {
            get {
                return ResourceManager.GetString("math0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null roundingMode 的本地化字符串。
        /// </summary>
        internal static string math10 {
            get {
                return ResourceManager.GetString("math10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radix out of range 的本地化字符串。
        /// </summary>
        internal static string math11 {
            get {
                return ResourceManager.GetString("math11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zero length BigInteger 的本地化字符串。
        /// </summary>
        internal static string math12 {
            get {
                return ResourceManager.GetString("math12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid signum value 的本地化字符串。
        /// </summary>
        internal static string math13 {
            get {
                return ResourceManager.GetString("math13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 signum-magnitude mismatch 的本地化字符串。
        /// </summary>
        internal static string math14 {
            get {
                return ResourceManager.GetString("math14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negative bit address 的本地化字符串。
        /// </summary>
        internal static string math15 {
            get {
                return ResourceManager.GetString("math15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negative exponent 的本地化字符串。
        /// </summary>
        internal static string math16 {
            get {
                return ResourceManager.GetString("math16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BigInteger divide by zero 的本地化字符串。
        /// </summary>
        internal static string math17 {
            get {
                return ResourceManager.GetString("math17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BigInteger: modulus not positive 的本地化字符串。
        /// </summary>
        internal static string math18 {
            get {
                return ResourceManager.GetString("math18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BigInteger not invertible. 的本地化字符串。
        /// </summary>
        internal static string math19 {
            get {
                return ResourceManager.GetString("math19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 start &lt; 0: {0} 的本地化字符串。
        /// </summary>
        internal static string math1A {
            get {
                return ResourceManager.GetString("math1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 numBits must be non-negative 的本地化字符串。
        /// </summary>
        internal static string math1B {
            get {
                return ResourceManager.GetString("math1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bitLength &lt; 2 的本地化字符串。
        /// </summary>
        internal static string math1C {
            get {
                return ResourceManager.GetString("math1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
